version: '3.1'
services:
    heartbeat_db:
        image: postgres:10.1-alpine
        restart: unless-stopped
        expose:
          - "5432"
        networks:
            - heart_net
        environment:
            - POSTGRES_USER=heartback
            - POSTGRES_PASSWORD=eKm7JkxzCF6MNg3NWh1l
            - POSTGRES_DB=HEART_BACK

    heartbeat_backend:
        build: .
        restart: unless-stopped
        ports:
            - "80:8080"
        networks:
            - heart_net

networks:
    heart_net:
