version: '3.1'
services:
    heartbeat_db:
        image: postgres:10.1-alpine
        restart: unless-stopped
        expose:
          - "5432"
        networks:
            - heart_net
        environment:
            - POSTGRES_USER=heartback
            - POSTGRES_PASSWORD=eKm7JkxzCF6MNg3NWh1l
            - POSTGRES_DB=HEART_BACK

    heartbeat_backend:
        build: ./
        restart: unless-stopped
        expose:
            - "8080"
        networks:
            - heart_net
            - app_net
        environment:
           - VIRTUAL_HOST=gspml2.die-softwareklitsche.de
           - LETSENCRYPT_HOST=gspml2.die-softwareklitsche.de, driver.die-softwareklitsche.de
           - LETSENCRYPT_EMAIL=admin@die-softwareklitsche.de

networks:
    heart_net:
    app_net:
        external: true
